// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb.proto

It has these top-level messages:
	LED
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LED struct {
	Serial uint64 `protobuf:"varint,1,opt,name=serial" json:"serial,omitempty"`
	Index  uint32 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Rgb    uint32 `protobuf:"fixed32,3,opt,name=rgb" json:"rgb,omitempty"`
	Render bool   `protobuf:"varint,4,opt,name=render" json:"render,omitempty"`
}

func (m *LED) Reset()                    { *m = LED{} }
func (m *LED) String() string            { return proto.CompactTextString(m) }
func (*LED) ProtoMessage()               {}
func (*LED) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LED) GetSerial() uint64 {
	if m != nil {
		return m.Serial
	}
	return 0
}

func (m *LED) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *LED) GetRgb() uint32 {
	if m != nil {
		return m.Rgb
	}
	return 0
}

func (m *LED) GetRender() bool {
	if m != nil {
		return m.Render
	}
	return false
}

func init() {
	proto.RegisterType((*LED)(nil), "LED")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0x48, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x57, 0x8a, 0xe5, 0x62, 0xf6, 0x71, 0x75, 0x11, 0x12, 0xe3, 0x62, 0x2b,
	0x4e, 0x2d, 0xca, 0x4c, 0xcc, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x82, 0xf2, 0x84, 0x44,
	0xb8, 0x58, 0x33, 0xf3, 0x52, 0x52, 0x2b, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x83, 0x20, 0x1c,
	0x21, 0x01, 0x2e, 0xe6, 0xa2, 0xf4, 0x24, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xf6, 0x20, 0x10, 0x13,
	0xa4, 0xbf, 0x28, 0x35, 0x2f, 0x25, 0xb5, 0x48, 0x82, 0x45, 0x81, 0x51, 0x83, 0x23, 0x08, 0xca,
	0x4b, 0x62, 0x03, 0xdb, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xef, 0xe0, 0xf0, 0x42, 0x71,
	0x00, 0x00, 0x00,
}
