/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pb.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pb.pb-c.h"
void   led__init
                     (LED         *message)
{
  static LED init_value = LED__INIT;
  *message = init_value;
}
size_t led__get_packed_size
                     (const LED *message)
{
  assert(message->base.descriptor == &led__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t led__pack
                     (const LED *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &led__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t led__pack_to_buffer
                     (const LED *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &led__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LED *
       led__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LED *)
     protobuf_c_message_unpack (&led__descriptor,
                                allocator, len, data);
}
void   led__free_unpacked
                     (LED *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &led__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor led__field_descriptors[2] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(LED, has_index),
    offsetof(LED, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rgb",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(LED, has_rgb),
    offsetof(LED, rgb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned led__field_indices_by_name[] = {
  0,   /* field[0] = index */
  1,   /* field[1] = rgb */
};
static const ProtobufCIntRange led__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor led__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LED",
  "LED",
  "LED",
  "",
  sizeof(LED),
  2,
  led__field_descriptors,
  led__field_indices_by_name,
  1,  led__number_ranges,
  (ProtobufCMessageInit) led__init,
  NULL,NULL,NULL    /* reserved[123] */
};
