esphome:
  name: laito
  platform: ESP8266
  board: nodemcuv2
  includes:
    - lifx-emulation.h
  libraries:
    - ESPAsyncUDP

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Lifx emulation needs UTC time to respond to packets correctly.  Code expects id: ha_time.
time:
  - platform: sntp
    id: ha_time

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    method: ESP8266_DMA
    pin: GPIO3
    num_leds: 60
    id: color_led
    name: "color_led"

logger:
  level: WARN
  esp8266_store_log_strings_in_flash: false

ota:

# Required component for Lifx support
custom_component:
- lambda: |-
    auto LifxLAN = new lifxUdp();
    WiFi.macAddress(LifxLAN->mac);

    LifxLAN->set_bulbLabel( App.get_name().c_str() );

    LifxLAN->set_bulbLocation( "Test Location" );
    LifxLAN->set_bulbLocationGUID( "4b833820-49b1-4f97-b324-316098f259d3" );
    LifxLAN->bulbLocationTime = 1600358586632000000;  // epoch in msec * 1,000,000

    LifxLAN->set_bulbGroup( "Test Group" );
    LifxLAN->set_bulbGroupGUID( "455820e8-3323-49f3-a7d0-598ba8092563" );
    LifxLAN->bulbGroupTime = 1600358586632000000; // epoch in msec * 1,000,000

    LifxLAN->beginUDP();
    return {LifxLAN};
